-- Migração 002: Seed estático legado neutralizado.
-- O motor de trackeamento agora inicia com 0 sites cadastrados por padrão (clean startup).
-- Para provisionar um site inicial declarativamente, configure SEED_DEFAULT_SITE=true no .env
-- ou adicione o primeiro site diretamente pelo Dashboard web.
